#
# default environment
#
spu
	-stdout.color 0.5 1.0 1.0 1.0
	-stdout.origin 5 -15
	-stdout.pitch 10
	-window 320 32 1280 720
	-base_path shaders:AA60/lib/gsys/shaders:media
gsys
	-drawcall.ub_material.albedo 1.0 1.0 1.0 1.0
	-drawcall.ub_material.roughness 0.8
	-drawcall.ub_material.metallic 0.2
	-drawcall.ub_material.ao 0.2
	-drawcall.flags.fill               1
	-drawcall.flags.blend              1
	-drawcall.flags.cull_face          1
	-drawcall.flags.ccw                1
	-drawcall.flags.depth_test         1
	-drawcall.flags.point_sprite       1
	-drawcall.flags.program_point_size 1
	
	-canvas.eye     -1.0 +1.0 +1.5
	-canvas.dir     +1.0 -0.7 -1.5
	-canvas.up      0.0  1.0  0.0 
	-canvas.near    0.01
	-canvas.far     1000.0
	-canvas.fovy    45

	-canvas.renderstate.flags.cull_face 0
	-canvas.renderstate.flags.blend 0
	-canvas.renderstate.flags.depth_test 0
	
	-canvas.bgcolor0  0.01 0.01 0.02 0 
	-canvas.bgdepth   1.0
	-canvas.bgstencil 0

	-canvas.shader.ub_light.ambient  0.5 0.5 0.5 1.0
	-canvas.shader.ub_light.sources[0].position  3.0 6.0 3.0 1.0
	-canvas.shader.ub_light.sources[0].direction 3.0 6.0 3.0 0.0
	-canvas.shader.ub_light.sources[0].emission  2.0 2.0 2.0 1.0
	-canvas.shader.ub_light.sources[0].radius    0.0
	-canvas.shader.ub_light.sources[0].decay     0.0
	-canvas.shader.ub_light.sources[0].exponent  0.0
	-canvas.shader.ub_light.sources[0].type      0
  
