# generate_ecc8to64_codebook.py
#
# 8bit -> 64bit のコードブックを生成して
# C++ ヘッダ ecc8to64_codebook.h を出力するスクリプトです。
#
# - 各コードは popcount=32（DCバランス）
# - コード間ハミング距離 >= MIN_DIST を目標とします。
#
# Python 3.8+ 前提（int.bit_count() を使用）

import random
from textwrap import indent

N_BITS = 64
N_CODES = 256
TARGET_POPCOUNT = 32  # 各コード内の1の数
MIN_DIST = 24         # ここを上げ下げして強さを調整

MAX_TRIES_PER_CODE = 100000  # 1コードあたりの最大試行回数
RNG_SEED = 123456789         # 再現性のためのシード


def popcount64(x: int) -> int:
    return x.bit_count()


def hamming_distance(a: int, b: int) -> int:
    return popcount64(a ^ b)


def random_balanced_code() -> int:
    """popcount=TARGET_POPCOUNT の 64bit コードをランダム生成"""
    positions = list(range(N_BITS))
    random.shuffle(positions)
    x = 0
    for i in range(TARGET_POPCOUNT):
        pos = positions[i]
        x |= (1 << pos)
    return x


def generate_codebook():
    random.seed(RNG_SEED)

    codes = []  # list[int]
    for m in range(N_CODES):
        print(f"[INFO] generating code for value {m} / {N_CODES-1}")
        for trial in range(MAX_TRIES_PER_CODE):
            cand = random_balanced_code()
            ok = True
            for c in codes:
                d = hamming_distance(c, cand)
                if d < MIN_DIST:
                    ok = False
                    break
            if ok:
                codes.append(cand)
                break
        else:
            # MAX_TRIES_PER_CODE を超えても見つからなかった場合
            raise RuntimeError(
                f"Failed to find codeword for value {m} with MIN_DIST={MIN_DIST}. "
                f"Try lowering MIN_DIST or increasing MAX_TRIES_PER_CODE."
            )
    return codes


def format_codebook_as_cpp(codes):
    """C++ ヘッダの文字列を返す"""
    lines = []
    lines.append("// This file was generated by generate_ecc8to64_codebook.py")
    lines.append("// 8-bit to 64-bit ECC codebook")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace ecc8to64 {")
    lines.append("")
    lines.append("inline constexpr std::uint64_t CODE_TABLE[256] = {")
    # 16個ずつ1行に並べる
    for i in range(0, N_CODES, 4):
        row = []
        for j in range(4):
            idx = i + j
            if idx >= N_CODES:
                break
            code = codes[idx]
            row.append(f"0x{code:016X}ull")
        line = "    " + ", ".join(row) + ("," if (i + 4 < N_CODES) else "")
        lines.append(line)
    lines.append("};")
    lines.append("")
    lines.append("} // namespace ecc8to64")
    lines.append("")
    return "\n".join(lines)


def main():
    codes = generate_codebook()
    header = format_codebook_as_cpp(codes)
    out_path = "ecc8to64_codebook.h"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
    print(f"[INFO] written codebook to {out_path}")


if __name__ == "__main__":
    main()
