//
// App :
//
#include "base_app.h"
namespace spu {
namespace {

/* clang-format off */
const char *c_vert = {
    "#version 420 core                                                                      \n"
    "uniform mat4 u_worldscreen;                                                             \n"
    "in vec2 a_position;                                                                    \n"
    "in vec2 a_texcoord;                                                                    \n"
    "out gl_PerVertex                                                                       \n"
    "{                                                                                      \n"
    "    vec4 gl_Position;                                                                  \n"
    "};                                                                                     \n"
    "out vec2 f_texcoord;                                                                   \n"
    "void main()                                                                            \n"
    "{                                                                                      \n"
    "    f_texcoord = a_texcoord;                                                           \n"
    "    gl_Position = u_worldscreen * vec4(a_position, 0.0, 1.0);                           \n"
    "}                                                                                      \n"
};
	
const char *c_frag = {
    "#version 420 core                                                                      \n"
    "//                                                                                     \n"
    "// -------------------- Library Start -------------------------------------            \n"
    "//                                                                                     \n"
    "vec4 hermite(const vec4 A, const vec4 B, const vec4 C, const vec4 D, const float S)    \n"
    "{                                                                                      \n"
    "    mat4 hermite = mat4(                                                               \n"
    "        vec4( 2,-3, 0, 1),                                                             \n"
    "        vec4(-2, 3, 0, 0),                                                             \n"
    "        vec4( 1,-2, 1, 0),                                                             \n"
    "        vec4( 1,-1, 0, 0));                                                            \n"
    "    vec4 expo = vec4(S * S * S, S * S, S, 1);                                          \n"
    "    return expo * hermite * mat4(                                                      \n"
    "        A[0], B[0], C[0], D[0],                                                        \n"
    "        A[1], B[1], C[1], D[1],                                                        \n"
    "        A[2], B[2], C[2], D[2],                                                        \n"
    "        A[3], B[3], C[3], D[3]);                                                       \n"
    "}                                                                                      \n"
    "vec4 bezier(const vec4 A, const vec4 B, const vec4 C, const vec4 D, const float S)     \n"
    "{                                                                                      \n"
    "    mat4 bezier = mat4(                                                                \n"
    "        vec4(-1, 3,-3, 1),                                                             \n"
    "        vec4( 3,-6, 3, 0),                                                             \n"
    "        vec4(-3, 3, 0, 0),                                                             \n"
    "        vec4( 1, 0, 0, 0));                                                            \n"
    "    vec4 expo = vec4(S * S * S, S * S, S, 1);                                          \n"
    "    return expo * bezier * mat4(                                                       \n"
    "        A[0], B[0], C[0], D[0],                                                        \n"
    "        A[1], B[1], C[1], D[1],                                                        \n"
    "        A[2], B[2], C[2], D[2],                                                        \n"
    "        A[3], B[3], C[3], D[3]);                                                       \n"
    "}                                                                                      \n"
    "vec4 catmullRom(const vec4 A, const vec4 B, const vec4 C, const vec4 D, const float S) \n"
    "{                                                                                      \n"
    "    mat4 catmullRom = mat4(                                                            \n"
    "        vec4(-1, 2,-1, 0),                                                             \n"
    "        vec4( 3,-5, 0, 2),                                                             \n"
    "        vec4(-3, 4, 1, 0),                                                             \n"
    "        vec4( 1,-1, 0, 0));                                                            \n"
    "    vec4 expo = vec4(S * S * S, S * S, S, 1);                                          \n"
    "    return 0.5 * expo * catmullRom * mat4(                                             \n"
    "        A[0], B[0], C[0], D[0],                                                        \n"
    "        A[1], B[1], C[1], D[1],                                                        \n"
    "        A[2], B[2], C[2], D[2],                                                        \n"
    "        A[3], B[3], C[3], D[3]);                                                       \n"
    "}                                                                                      \n"
    "vec2 mirrorRepeat(const vec2 texcoord)                                                 \n"
    "{                                                                                      \n"
    "    vec2 clamp_v = vec2(ivec2(floor(texcoord)) % ivec2(2));                            \n"
    "    vec2 floor_v = floor(texcoord);                                                    \n"
    "    vec2 rest = texcoord - floor_v;                                                    \n"
    "    vec2 mirror = clamp_v + rest;                                                      \n"
    "    return mix(vec2(1) - rest, rest, greaterThanEqual(mirror, vec2(1)));               \n"
    "}                                                                                      \n"
    "float textureLevel(in sampler2D sampler, const vec2 texcoord)                          \n"
    "{                                                                                      \n"
    "    vec2 texture_size = vec2(textureSize(sampler, 0));                                 \n"
    "    float levelCount = max(log2(texture_size.x), log2(texture_size.y));                \n"
    "    vec2 dx = dFdx(texcoord * texture_size);                                           \n"
    "    vec2 dy = dFdy(texcoord * texture_size);                                           \n"
    "    float d = max(dot(dx, dx), dot(dy, dy));                                           \n"
    "    d = clamp(d, 1.0, pow(2, (levelCount - 1) * 2));                                   \n"
    "    return 0.5 * log2(d);                                                              \n"
    "}                                                                                      \n"

    
    "vec4 fetchBilinear(                                                                    \n"
    "    in sampler2D sampler, const vec2 interpolant, in ivec2 texelcoords[4], const int lod)\n"
    "{                                                                                      \n"
    "    vec4 texel00 = texelFetch(sampler, texelcoords[0], lod);                           \n"
    "    vec4 texel10 = texelFetch(sampler, texelcoords[1], lod);                           \n"
    "    vec4 texel11 = texelFetch(sampler, texelcoords[2], lod);                           \n"
    "    vec4 texel01 = texelFetch(sampler, texelcoords[3], lod);                           \n"
    "    vec4 texel0 = mix(texel00, texel01, interpolant.y);                                \n"
    "    vec4 texel1 = mix(texel10, texel11, interpolant.y);                                \n"
    "    return mix(texel0, texel1, interpolant.x);                                         \n"
    "}                                                                                      \n"
    "///////////////                                                                        \n"
    "// Nearest                                                                             \n"
    "vec4 textureNearest(                                                                   \n"
    "    in sampler2D sampler, const vec2 texcoord)                                         \n"
    "{                                                                                      \n"
    "    int lodNearest = int(round(textureQueryLod(sampler, texcoord).x));                 \n"
    "    ivec2 texture_size = textureSize(sampler, lodNearest);                             \n"
    "    ivec2 texelcoord = ivec2(texture_size * texcoord);                                 \n"
    "    return texelFetch(sampler, texelcoord, lodNearest);                                \n"
    "}                                                                                      \n"
    "vec4 textureNearestLod(                                                                \n"
    "    in sampler2D sampler, const vec2 texcoord, const float lod)                        \n"
    "{                                                                                      \n"
    "    int lodNearest = int(round(lod));                                                  \n"
    "    ivec2 texture_size = textureSize(sampler, lodNearest);                             \n"
    "    ivec2 texelcoord = ivec2(texture_size * texcoord);                                 \n"
    "    return texelFetch(sampler, texelcoord, lodNearest);                                \n"
    "}                                                                                      \n"
    "vec4 textureNearestLod(                                                                \n"
    "    in sampler2D sampler, const vec2 texcoord, const int lod)                          \n"
    "{                                                                                      \n"
    "    ivec2 texture_size = textureSize(sampler, lod);                                    \n"
    "    ivec2 texelcoord = ivec2(texture_size * texcoord);                                 \n"
    "    return texelFetch(sampler, texelcoord, lod);                                       \n"
    "}                                                                                      \n"
    "vec4 textureNearestLodRepeat(                                                          \n"
    "    in sampler2D sampler, const vec2 texcoord, const float lod)                        \n"
    "{                                                                                      \n"
    "    int lodNearest = int(round(lod));                                                  \n"
    "    ivec2 size = textureSize(sampler, lodNearest);                                     \n"
    "    ivec2 texture_size = textureSize(sampler, lodNearest);                             \n"
    "    ivec2 texelcoord = ivec2(texture_size * texcoord) % size;                          \n"
    "    return texelFetch(sampler, texelcoord, lodNearest);                                \n"
    "}                                                                                      \n"

    "///////////////                                                                        \n"
    "// Bilinear                                                                            \n"
    "vec4 textureBilinear(                                                                  \n"
    "    in sampler2D sampler, const vec2 texcoord)                                         \n"
    "{                                                                                      \n"
    "    int lod = int(round(textureQueryLod(sampler, texcoord).x));                        \n"
    "    ivec2 size = textureSize(sampler, lod);                                            \n"
    "    vec2 texelcoord = texcoord * size - 0.5;                                           \n"
    "    ivec2 texelIndex = ivec2(texelcoord);                                              \n"
    "    ivec2 texelcoords[] = ivec2[4](                                                    \n"
    "        texelIndex + ivec2(0, 0),                                                      \n"
    "        texelIndex + ivec2(1, 0),                                                      \n"
    "        texelIndex + ivec2(1, 1),                                                      \n"
    "        texelIndex + ivec2(0, 1));                                                     \n"
    "    return fetchBilinear(                                                              \n"
    "        sampler,                                                                       \n"
    "        fract(texelcoord),                                                             \n"
    "        texelcoords,                                                                   \n"
    "        lod);                                                                          \n"
    "}                                                                                      \n"
    "vec4 textureBilinearLod(                                                               \n"
    "    in sampler2D sampler, const vec2 texcoord, const int lod)                          \n"
    "{                                                                                      \n"
    "    ivec2 size = textureSize(sampler, lod);                                            \n"
    "    vec2 texelcoord = texcoord * size - 0.5;                                           \n"
    "    ivec2 texelIndex = ivec2(texelcoord);                                              \n"
    "    ivec2 texelcoords[] = ivec2[4](                                                    \n"
    "        texelIndex + ivec2(0, 0),                                                      \n"
    "        texelIndex + ivec2(1, 0),                                                      \n"
    "        texelIndex + ivec2(1, 1),                                                      \n"
    "        texelIndex + ivec2(0, 1));                                                     \n"
    "    return fetchBilinear(                                                              \n"
    "        sampler,                                                                       \n"
    "        fract(texelcoord),                                                             \n"
    "        texelcoords,                                                                   \n"
    "        lod);                                                                          \n"
    "}                                                                                      \n"
    "vec4 textureBilinearLodRepeat(                                                         \n"
    "    in sampler2D sampler, const vec2 texcoord, const int lod)                          \n"
    "{                                                                                      \n"
    "    ivec2 size = textureSize(sampler, lod);                                            \n"
    "    vec2 texelcoord = texcoord * size - 0.5;                                           \n"
    "    ivec2 texelIndex = ivec2(texelcoord);                                              \n"
    "    ivec2 texelcoords[] = ivec2[4](                                                    \n"
    "        (texelIndex + ivec2(0, 0)) % size,                                             \n"
    "        (texelIndex + ivec2(1, 0)) % size,                                             \n"
    "        (texelIndex + ivec2(1, 1)) % size,                                             \n"
    "        (texelIndex + ivec2(0, 1)) % size);                                            \n"
    "    return fetchBilinear(                                                              \n"
    "        sampler,                                                                       \n"
    "        fract(texelcoord),                                                             \n"
    "        texelcoords,                                                                   \n"
    "        lod);                                                                          \n"
    "}                                                                                      \n"
    "vec4 textureBilinearLodMirrorRepeat(                                                   \n"
    "    in sampler2D sampler, const vec2 texcoord, const int lod)                          \n"
    "{                                                                                      \n"
    "    ivec2 size = textureSize(sampler, lod);                                            \n"
    "    vec2 texelcoord = mirrorRepeat(texcoord) * size - 0.5;                             \n"
    "    ivec2 texelIndex = ivec2(texelcoord);                                              \n"
    "    ivec2 texelcoords[] = ivec2[4](                                                    \n"
    "        (texelIndex + ivec2(0, 0)) % size,                                             \n"
    "        (texelIndex + ivec2(1, 0)) % size,                                             \n"
    "        (texelIndex + ivec2(1, 1)) % size,                                             \n"
    "        (texelIndex + ivec2(0, 1)) % size);                                            \n"
    "    return fetchBilinear(                                                              \n"
    "        sampler,                                                                       \n"
    "        fract(texelcoord),                                                             \n"
    "        texelcoords,                                                                   \n"
    "        lod);                                                                          \n"
    "}                                                                                      \n"
    "vec4 textureBilinearLodClampToBorder(                                                  \n"
    "    in sampler2D sampler, const vec2 texcoord, const int lod)                          \n"
    "{                                                                                      \n"
    "    ivec2 size = textureSize(sampler, lod);                                            \n"
    "    vec2 texelcoord = clamp(texcoord, 0, 1) * size - 0.5;                              \n"
    "    ivec2 texelIndex = ivec2(texelcoord);                                              \n"
    "    ivec2 texelcoords[] = ivec2[4](                                                    \n"
    "        clamp(texelIndex + ivec2(0, 0), ivec2(0), size - 1),                           \n"
    "        clamp(texelIndex + ivec2(1, 0), ivec2(0), size - 1),                           \n"
    "        clamp(texelIndex + ivec2(1, 1), ivec2(0), size - 1),                           \n"
    "        clamp(texelIndex + ivec2(0, 1), ivec2(0), size - 1));                          \n"
    "    return fetchBilinear(                                                              \n"
    "        sampler,                                                                       \n"
    "        fract(texelcoord),                                                             \n"
    "        texelcoords,                                                                   \n"
    "        lod);                                                                          \n"
    "}                                                                                      \n"
    "///////////////                                                                        \n"
    "// Trilinear                                                                           \n"
    "vec4 textureTrilinear(                                                                 \n"
    "    in sampler2D sampler, const vec2 texcoord)                                         \n"
    "{                                                                                      \n"
    "    float lod = textureQueryLod(sampler, texcoord).x;                                  \n"
    "    int lodMin = int(floor(lod));                                                      \n"
    "    int lodMax = int(ceil(lod));                                                       \n"
    "    vec4 texelMin = textureBilinearLod(sampler, texcoord, lodMin);                     \n"
    "    vec4 texelMax = textureBilinearLod(sampler, texcoord, lodMax);                     \n"
    "    return mix(texelMin, texelMax, fract(lod));                                        \n"
    "}                                                                                      \n"
    "vec4 textureTrilinearLod(                                                              \n"
    "    in sampler2D sampler, const vec2 texcoord, const float lod)                        \n"
    "{                                                                                      \n"
    "    int lodMin = int(floor(lod));                                                      \n"
    "    int lodMax = int(ceil(lod));                                                       \n"
    "    vec4 texelMin = textureBilinearLod(sampler, texcoord, lodMin);                     \n"
    "    vec4 texelMax = textureBilinearLod(sampler, texcoord, lodMax);                     \n"
    "    return mix(texelMin, texelMax, fract(lod));                                        \n"
    "}                                                                                      \n"
    "vec4 textureTrilinearLodRepeat(                                                        \n"
    "    in sampler2D sampler, const vec2 texcoord, const float lod)                        \n"
    "{                                                                                      \n"
    "    int lodMin = int(floor(lod));                                                      \n"
    "    int lodMax = int(ceil(lod));                                                       \n"
    "    vec4 texelMin = textureBilinearLodRepeat(sampler, texcoord, lodMin);               \n"
    "    vec4 texelMax = textureBilinearLodRepeat(sampler, texcoord, lodMax);               \n"
    "    return mix(texelMin, texelMax, fract(lod));                                        \n"
    "}                                                                                      \n"
    "vec4 textureTrilinearLodMirrorRepeat(                                                  \n"
    "    in sampler2D sampler, const vec2 texcoord, const float lod)                        \n"
    "{                                                                                      \n"
    "    int lodMin = int(floor(lod));                                                      \n"
    "    int lodMax = int(ceil(lod));                                                       \n"
    "    vec4 texelMin = textureBilinearLodMirrorRepeat(sampler, texcoord, lodMin);         \n"
    "    vec4 texelMax = textureBilinearLodMirrorRepeat(sampler, texcoord, lodMax);         \n"
    "    return mix(texelMin, texelMax, fract(lod));                                        \n"
    "}                                                                                      \n"
    "vec4 textureTrilinearLodClampToBorder(                                                 \n"
    "    in sampler2D sampler, const vec2 texcoord, const float lod)                        \n"
    "{                                                                                      \n"
    "    int lodMin = int(floor(lod));                                                      \n"
    "    int lodMax = int(ceil(lod));                                                       \n"
    "    vec4 texelMin = textureBilinearLodClampToBorder(sampler, texcoord, lodMin);        \n"
    "    vec4 texelMax = textureBilinearLodClampToBorder(sampler, texcoord, lodMax);        \n"
    "    return mix(texelMin, texelMax, fract(lod));                                        \n"
    "}                                                                                      \n"
    "///////////////                                                                        \n"
    "// Bicubic                                                                             \n"
    "vec4 textureBicubicLod(                                                                \n"
    "    in sampler2D sampler, const vec2 texcoord, const int lod)                          \n"
    "{                                                                                      \n"
    "    ivec2 size = textureSize(sampler, lod);                                            \n"
    "    vec2 texelcoord = texcoord * size - 0.5;                                           \n"
    "    ivec2 texelIndex = ivec2(texelcoord);                                              \n"
    "    vec4 texel00 = texelFetch(sampler, texelIndex + ivec2(-1,-1), lod);                \n"
    "    vec4 texel10 = texelFetch(sampler, texelIndex + ivec2( 0,-1), lod);                \n"
    "    vec4 texel20 = texelFetch(sampler, texelIndex + ivec2( 1,-1), lod);                \n"
    "    vec4 texel30 = texelFetch(sampler, texelIndex + ivec2( 2,-1), lod);                \n"
    "    vec4 texel01 = texelFetch(sampler, texelIndex + ivec2(-1, 0), lod);                \n"
    "    vec4 texel11 = texelFetch(sampler, texelIndex + ivec2( 0, 0), lod);                \n"
    "    vec4 texel21 = texelFetch(sampler, texelIndex + ivec2( 1, 0), lod);                \n"
    "    vec4 texel31 = texelFetch(sampler, texelIndex + ivec2( 2, 0), lod);                \n"
    "    vec4 texel02 = texelFetch(sampler, texelIndex + ivec2(-1, 1), lod);                \n"
    "    vec4 texel12 = texelFetch(sampler, texelIndex + ivec2( 0, 1), lod);                \n"
    "    vec4 texel22 = texelFetch(sampler, texelIndex + ivec2( 1, 1), lod);                \n"
    "    vec4 texel32 = texelFetch(sampler, texelIndex + ivec2( 2, 1), lod);                \n"
    "    vec4 texel03 = texelFetch(sampler, texelIndex + ivec2(-1, 2), lod);                \n"
    "    vec4 texel13 = texelFetch(sampler, texelIndex + ivec2( 0, 2), lod);                \n"
    "    vec4 texel23 = texelFetch(sampler, texelIndex + ivec2( 1, 2), lod);                \n"
    "    vec4 texel33 = texelFetch(sampler, texelIndex + ivec2( 2, 2), lod);                \n"
    "    vec2 splinecoord = fract(texelcoord);                                              \n"
    "    vec4 row0 = catmullRom(texel00, texel10, texel20, texel30, splinecoord.x);         \n"
    "    vec4 row1 = catmullRom(texel01, texel11, texel21, texel31, splinecoord.x);         \n"
    "    vec4 row2 = catmullRom(texel02, texel12, texel22, texel32, splinecoord.x);         \n"
    "    vec4 row3 = catmullRom(texel03, texel13, texel23, texel33, splinecoord.x);         \n"
    "    return catmullRom(row0, row1, row2, row3, splinecoord.y);                          \n"
    "}                                                                                      \n"
    "vec4 textureBicubicLodRepeat(                                                          \n"
    "    in sampler2D sampler, const vec2 texcoord, const int lod)                          \n"
    "{                                                                                      \n"
    "    ivec2 size = textureSize(sampler, lod);                                            \n"
    "    vec2 texelcoord = texcoord * size - 0.5;                                           \n"
    "    ivec2 texelIndex = ivec2(texelcoord);                                              \n"
    "    vec4 texel00 = texelFetch(sampler, (texelIndex + ivec2(-1,-1)) % size, lod);       \n"
    "    vec4 texel10 = texelFetch(sampler, (texelIndex + ivec2( 0,-1)) % size, lod);       \n"
    "    vec4 texel20 = texelFetch(sampler, (texelIndex + ivec2( 1,-1)) % size, lod);       \n"
    "    vec4 texel30 = texelFetch(sampler, (texelIndex + ivec2( 2,-1)) % size, lod);       \n"
    "    vec4 texel01 = texelFetch(sampler, (texelIndex + ivec2(-1, 0)) % size, lod);       \n"
    "    vec4 texel11 = texelFetch(sampler, (texelIndex + ivec2( 0, 0)) % size, lod);       \n"
    "    vec4 texel21 = texelFetch(sampler, (texelIndex + ivec2( 1, 0)) % size, lod);       \n"
    "    vec4 texel31 = texelFetch(sampler, (texelIndex + ivec2( 2, 0)) % size, lod);       \n"
    "    vec4 texel02 = texelFetch(sampler, (texelIndex + ivec2(-1, 1)) % size, lod);       \n"
    "    vec4 texel12 = texelFetch(sampler, (texelIndex + ivec2( 0, 1)) % size, lod);       \n"
    "    vec4 texel22 = texelFetch(sampler, (texelIndex + ivec2( 1, 1)) % size, lod);       \n"
    "    vec4 texel32 = texelFetch(sampler, (texelIndex + ivec2( 2, 1)) % size, lod);       \n"
    "    vec4 texel03 = texelFetch(sampler, (texelIndex + ivec2(-1, 2)) % size, lod);       \n"
    "    vec4 texel13 = texelFetch(sampler, (texelIndex + ivec2( 0, 2)) % size, lod);       \n"
    "    vec4 texel23 = texelFetch(sampler, (texelIndex + ivec2( 1, 2)) % size, lod);       \n"
    "    vec4 texel33 = texelFetch(sampler, (texelIndex + ivec2( 2, 2)) % size, lod);       \n"
    "    vec2 splinecoord = fract(texelcoord);                                              \n"
    "    vec4 row0 = catmullRom(texel00, texel10, texel20, texel30, splinecoord.x);         \n"
    "    vec4 row1 = catmullRom(texel01, texel11, texel21, texel31, splinecoord.x);         \n"
    "    vec4 row2 = catmullRom(texel02, texel12, texel22, texel32, splinecoord.x);         \n"
    "    vec4 row3 = catmullRom(texel03, texel13, texel23, texel33, splinecoord.x);         \n"
    "    return catmullRom(row0, row1, row2, row3, splinecoord.y);                          \n"
    "}                                                                                      \n"
    "vec4 textureBicubicLodRepeat2(                                                         \n"
    "    in sampler2D sampler, const vec2 texcoord, const int lod)                          \n"
    "{                                                                                      \n"
    "    ivec2 size = textureSize(sampler, lod);                                            \n"
    "    vec2 texelcoord = texcoord * size - 1.5;                                           \n"
    "    ivec2 texelIndex = ivec2(texelcoord);                                              \n"
    "    vec4 texel00 = texelFetch(sampler, (texelIndex + ivec2(0, 0)) % size, lod);        \n"
    "    vec4 texel10 = texelFetch(sampler, (texelIndex + ivec2(1, 0)) % size, lod);        \n"
    "    vec4 texel20 = texelFetch(sampler, (texelIndex + ivec2(2, 0)) % size, lod);        \n"
    "    vec4 texel30 = texelFetch(sampler, (texelIndex + ivec2(3, 0)) % size, lod);        \n"
    "    vec4 texel01 = texelFetch(sampler, (texelIndex + ivec2(0, 1)) % size, lod);        \n"
    "    vec4 texel11 = texelFetch(sampler, (texelIndex + ivec2(1, 1)) % size, lod);        \n"
    "    vec4 texel21 = texelFetch(sampler, (texelIndex + ivec2(2, 1)) % size, lod);        \n"
    "    vec4 texel31 = texelFetch(sampler, (texelIndex + ivec2(3, 1)) % size, lod);        \n"
    "    vec4 texel02 = texelFetch(sampler, (texelIndex + ivec2(0, 2)) % size, lod);        \n"
    "    vec4 texel12 = texelFetch(sampler, (texelIndex + ivec2(1, 2)) % size, lod);        \n"
    "    vec4 texel22 = texelFetch(sampler, (texelIndex + ivec2(2, 2)) % size, lod);        \n"
    "    vec4 texel32 = texelFetch(sampler, (texelIndex + ivec2(3, 2)) % size, lod);        \n"
    "    vec4 texel03 = texelFetch(sampler, (texelIndex + ivec2(0, 3)) % size, lod);        \n"
    "    vec4 texel13 = texelFetch(sampler, (texelIndex + ivec2(1, 3)) % size, lod);        \n"
    "    vec4 texel23 = texelFetch(sampler, (texelIndex + ivec2(2, 3)) % size, lod);        \n"
    "    vec4 texel33 = texelFetch(sampler, (texelIndex + ivec2(3, 3)) % size, lod);        \n"
    "    vec2 splinecoord = fract(texelcoord);                                              \n"
    "    vec4 row0 = catmullRom(texel00, texel10, texel20, texel30, splinecoord.x);         \n"
    "    vec4 row1 = catmullRom(texel01, texel11, texel21, texel31, splinecoord.x);         \n"
    "    vec4 row2 = catmullRom(texel02, texel12, texel22, texel32, splinecoord.x);         \n"
    "    vec4 row3 = catmullRom(texel03, texel13, texel23, texel33, splinecoord.x);         \n"
    "    return catmullRom(row0, row1, row2, row3, splinecoord.y);                          \n"
    "}                                                                                      \n"
    "vec4 textureBicubicLinearLodRepeat(                                                    \n"
    "    in sampler2D sampler, const vec2 texcoord, const float lod)                        \n"
    "{                                                                                      \n"
    "    int lodMin = int(floor(lod));                                                      \n"
    "    int lodMax = int(ceil(lod));                                                       \n"
    "    vec4 texelMin = textureBicubicLodRepeat(sampler, texcoord, lodMin);                \n"
    "    vec4 texelMax = textureBicubicLodRepeat(sampler, texcoord, lodMax);                \n"
    "    return mix(texelMin, texelMax, fract(lod));                                        \n"
    "}                                                                                      \n"
    "///////////////                                                                        \n"
    "// Tricubic                                                                            \n"
    "vec4 textureTricubicLodRepeat(                                                         \n"
    "    in sampler2D sampler, const vec2 texcoord, const float lod)                        \n"
    "{                                                                                      \n"
    "    int lodMin = int(floor(lod));                                                      \n"
    "    int lodMax = int(ceil(lod));                                                       \n"
    "    vec4 texelA = textureBicubicLodRepeat(sampler, texcoord, max(lodMin - 1, 0));      \n"
    "    vec4 texelB = textureBicubicLodRepeat(sampler, texcoord, lodMin);                  \n"
    "    vec4 texelC = textureBicubicLodRepeat(sampler, texcoord, lodMax);                  \n"
    "    vec4 texelD = textureBicubicLodRepeat(sampler, texcoord, lodMax + 1);              \n"
    "    return catmullRom(texelA, texelB, texelC, texelD, fract(lod));                     \n"
    "}                                                                                      \n"
    "/////////////////////                                                                  \n"
    "// Color procesing                                                                     \n"
    "vec4 squeeze(const vec4 color, const float ratio)                                      \n"
    "{                                                                                      \n"
    "    return color * (1.0 - ratio) + (ratio * 0.5);                                      \n"
    "}                                                                                      \n"
    "//                                                                                     \n"
    "// -------------------- Library End -------------------------------------              \n"
    "//                                                                                     \n"
    "uniform sampler2D u_diffuse;                                                           \n"
    "in vec2 f_texcoord;                                                                    \n"
    "layout(location = 0, index = 0) out vec4 color;                                        \n"
    "vec4 textureTrilinear(in sampler2D sampler, const vec2 texcoord);                      \n"
    "vec4 textureBicubicLod(in sampler2D sampler, const vec2 texcoord, const int lod);      \n"
    "void main()                                                                            \n"
    "{                                                                                      \n"
    "    //color = textureTrilinear(u_diffuse, f_texcoord);                                 \n"
    "    color = textureBicubicLod(u_diffuse, f_texcoord, 0);                               \n"
    "}                                                                                      \n"
};

/* clang-format on */
class App : public BaseApp {
public:
	SpuShader m_shader;
	Mat4f u_worldscreen;
	uint32_t u_diffuse;
	uint32_t m_arrayId;

	App(const char *name) : BaseApp(name, true, c_orange) {}

	void init(const Attrs &attrs) override
	{
		BaseApp::init(attrs);

		// program
		{
			Attrs shader_attrs = {
			        {"vert", c_vert},
			        {"frag", c_frag},
			};
			Attrs unif_attrs = {
			        {"u_worldscreen", &u_worldscreen},
			        {"u_diffuse",     &u_diffuse    },
			};
			loadShader(m_shader, shader_attrs, unif_attrs);
		}
		// array #0
		{
			Attrs attrs = {
			        {"shader_id",    m_shader.id()},
			        {"a.a_position", 2            },
			        {"a.a_texcoord", 2            },
			};
			m_arrayId = squareQuadsArray<v2fv2f_t>(attrs);
		}
		// texture
		{
			u_diffuse = loadDDS("kueken7_rgba_dxt5_unorm.dds");
		}
	}

	void render() override
	{
		getCamera().setViewscreen(viewport(0), 45, 0.1, 1000.0);
		u_worldscreen = getCamera().worldscreen();
		m_shader.use();
		spu_array_draw(m_arrayId, GL_TRIANGLES);
	}
};

static ObjectRegistry<SpuPage>::Creator<App> spu_sketch_creator("gl_420_sampler_fetch");
}  // namespace
}  // namespace spu
