//
//
//
namespace {
/* clang-format off */
const char *c_vert = {
    "#version 410 core                                                                      \n"
    "uniform mat4 u_worldscreen;                                                             \n"
    "layout(location = 0) in vec2 a_position;                                               \n"
    "layout(location = 3) in vec4 a_color;                                                  \n"
    "out gl_PerVertex                                                                       \n"
    "{                                                                                      \n"
    "    vec4 gl_Position;                                                                  \n"
    "    float gl_PointSize;                                                                \n"
    "    float gl_ClipDistance[];                                                           \n"
    "};                                                                                     \n"
    "struct vertex                                                                          \n"
    "{                                                                                      \n"
    "    vec4 Color;                                                                        \n"
    "};                                                                                     \n"
    "layout(location = 0) out vertex Out;                                                   \n"
    "void main()                                                                            \n"
    "{                                                                                      \n"
    "    gl_Position = u_worldscreen * vec4(a_position, 0.0, 1.0);                           \n"
    "    Out.Color = a_color;                                                               \n"
    "}                                                                                      \n"
};

const char *c_tesc = {
    "#version 410 core                                                                      \n"
    "layout(vertices = 4) out;                                                              \n"
    "struct vertex                                                                          \n"
    "{                                                                                      \n"
    "    vec4 Color;                                                                        \n"
    "};                                                                                     \n"
    "in gl_PerVertex                                                                        \n"
    "{                                                                                      \n"
    "    vec4 gl_Position;                                                                  \n"
    "    float gl_PointSize;                                                                \n"
    "    float gl_ClipDistance[];                                                           \n"
    "} gl_in[];                                                                             \n"
    "layout(location = 0) in vertex In[];                                                   \n"
    "out gl_PerVertex                                                                       \n"
    "{                                                                                      \n"
    "    vec4 gl_Position;                                                                  \n"
    "    float gl_PointSize;                                                                \n"
    "    float gl_ClipDistance[];                                                           \n"
    "} gl_out[];                                                                            \n"
    "layout(location = 0) out vertex Out[];                                                 \n"
    "void main()                                                                            \n"
    "{                                                                                      \n"
    "    gl_TessLevelInner[0] = 16.0;                                                       \n"
    "    gl_TessLevelInner[1] = 16.0;                                                       \n"
    "    gl_TessLevelOuter[0] = 8.0;                                                        \n"
    "    gl_TessLevelOuter[1] = 8.0;                                                        \n"
    "    gl_TessLevelOuter[2] = 8.0;                                                        \n"
    "    gl_TessLevelOuter[3] = 8.0;                                                        \n"
    "    gl_out[gl_InvocationID].gl_Position = gl_in[gl_InvocationID].gl_Position;          \n"
    "    Out[gl_InvocationID].Color = In[gl_InvocationID].Color;                            \n"
    "}                                                                                      \n"
};

const char *c_tese = {
    "#version 410 core                                                                      \n"
    "layout(quads, equal_spacing, ccw) in;                                                  \n"
    "struct vertex                                                                          \n"
    "{                                                                                      \n"
    "    vec4 Color;                                                                        \n"
    "};                                                                                     \n"
    "in gl_PerVertex                                                                        \n"
    "{                                                                                      \n"
    "    vec4 gl_Position;                                                                  \n"
    "    float gl_PointSize;                                                                \n"
    "    float gl_ClipDistance[];                                                           \n"
    "} gl_in[];                                                                             \n"
    "layout(location = 0) in vertex In[];                                                   \n"
    "out gl_PerVertex                                                                       \n"
    "{                                                                                      \n"
    "    vec4 gl_Position;                                                                  \n"
    "    float gl_PointSize;                                                                \n"
    "    float gl_ClipDistance[];                                                           \n"
    "};                                                                                     \n"
    "layout(location = 0) out vertex Out;                                                   \n"
    "vec4 interpolate(in vec4 v0, in vec4 v1, in vec4 v2, in vec4 v3)                       \n"
    "{                                                                                      \n"
    "    vec4 a = mix(v0, v1, gl_TessCoord.x);                                              \n"
    "    vec4 b = mix(v3, v2, gl_TessCoord.x);                                              \n"
    "    return mix(a, b, gl_TessCoord.y);                                                  \n"
    "}                                                                                      \n"
    "void main()                                                                            \n"
    "{                                                                                      \n"
    "    gl_Position = interpolate(                                                         \n"
    "               gl_in[0].gl_Position,                                                   \n"
    "               gl_in[1].gl_Position,                                                   \n"
    "               gl_in[2].gl_Position,                                                   \n"
    "               gl_in[3].gl_Position);                                                  \n"
    "    Out.Color = interpolate(                                                           \n"
    "               In[0].Color,                                                            \n"
    "               In[1].Color,                                                            \n"
    "               In[2].Color,                                                            \n"
    "               In[3].Color);                                                           \n"
    "}                                                                                      \n"
};

const char *c_geom = {

    "#version 410 core                                                                      \n"
    "layout(triangles, invocations = 1) in;                                                 \n"
    "layout(triangle_strip, max_vertices = 4) out;                                          \n"
    "in gl_PerVertex                                                                        \n"
    "{                                                                                      \n"
    "    vec4 gl_Position;                                                                  \n"
    "    float gl_PointSize;                                                                \n"
    "    float gl_ClipDistance[];                                                           \n"
    "} gl_in[];                                                                             \n"
    "struct vertex                                                                          \n"
    "{                                                                                      \n"
    "    vec4 Color;                                                                        \n"
    "};                                                                                     \n"
    "layout(location = 0) in vertex In[];                                                   \n"
    "out gl_PerVertex                                                                       \n"
    "{                                                                                      \n"
    "    vec4 gl_Position;                                                                  \n"
    "    float gl_PointSize;                                                                \n"
    "    float gl_ClipDistance[];                                                           \n"
    "};                                                                                     \n"
    "layout(location = 0) out vertex Out;                                                   \n"
    "void main()                                                                            \n"
    "{                                                                                      \n"
    "    for(int i = 0; i < gl_in.length(); ++i)                                            \n"
    "    {                                                                                  \n"
    "        gl_Position = gl_in[i].gl_Position;                                            \n"
    "        Out.Color = In[i].Color;                                                       \n"
    "        EmitVertex();                                                                  \n"
    "    }                                                                                  \n"
    "    EndPrimitive();                                                                    \n"
    "}                                                                                      \n"
};
	
const char *c_frag = {
    "#version 410 core                                                                      \n"
    "struct vertex                                                                          \n"
    "{                                                                                      \n"
    "    vec4 Color;                                                                        \n"
    "};                                                                                     \n"
    "layout(location = 0) in vertex In;                                                     \n"
    "layout(location = 0, index = 0) out vec4 FragColor;                                    \n"
    "void main()                                                                            \n"
    "{                                                                                      \n"
    "    FragColor = In.Color;                                                              \n"
    "}                                                                                      \n"
};
} // namespace
