
set(sources
  gl_300_fbo_multisample.cpp 
  gl_300_test_alpha.cpp 
  gl_320_buffer_uniform_shared.cpp 
  gl_320_buffer_uniform.cpp 
  gl_320_buffer_update.cpp 
  gl_320_draw_base_vertex.cpp 
  gl_320_draw_image_space.cpp 
  gl_320_draw_instanced.cpp 
  gl_320_draw_multiple.cpp 
  gl_320_draw_range_arrays.cpp 
  gl_320_draw_range_elements.cpp 
  gl_320_draw_without_vertex_attrib.cpp 
  gl_320_fbo_blend.cpp 
  gl_320_fbo_depth_multisample.cpp 
  gl_320_fbo_depth_stencil.cpp 
  gl_320_fbo_depth.cpp 
  gl_320_fbo_integer_blit.cpp 
  gl_320_fbo_integer.cpp 
  gl_320_fbo_layered.cpp 
  gl_320_fbo_multisample_explicit.cpp 
  gl_320_fbo_multisample_integer.cpp 
  gl_320_fbo_multisample.cpp 
  gl_320_fbo_rtt_texture_array.cpp 
  gl_320_fbo_rtt.cpp 
  gl_320_fbo_shadow.cpp 
  gl_320_fbo_srgb_blend.cpp 
  gl_320_fbo_srgb_decode_ext.cpp 
  gl_320_fbo_srgb.cpp 
  gl_320_fbo.cpp 
  gl_320_glsl_builtin_blocks.cpp 
  gl_320_glsl_cast_fail.cpp 
  gl_320_glsl_discard.cpp 
  gl_320_primitive_front_face.cpp 
  gl_320_primitive_line_msaa.cpp 
  gl_320_primitive_point_clip.cpp 
  gl_320_primitive_point_quad.cpp 
  gl_320_primitive_point.cpp 
  gl_320_primitive_shading.cpp 
  gl_320_primitive_sprite.cpp 
  gl_320_program_uniform.cpp 
  gl_320_program.cpp 
  gl_320_query_conditional.cpp 
  gl_320_query_occlusion.cpp 
  gl_320_sync.cpp 
  gl_320_test_scissor.cpp 
  gl_320_texture_2d.cpp 
  gl_320_texture_3d.cpp 
  gl_320_texture_buffer.cpp 
  gl_320_texture_compressed_ext.cpp 
  gl_320_texture_cube.cpp 
  gl_320_texture_derivative.cpp 
  gl_320_texture_fetch.cpp 
  gl_320_texture_float.cpp 
  gl_320_texture_format.cpp 
  gl_320_texture_integer.cpp 
  gl_320_texture_lod.cpp 
  gl_320_texture_offset.cpp 
  gl_320_texture_pixel_store.cpp 
  gl_320_texture_streaming.cpp 
  gl_320_transform_feedback.cpp 
  gl_330_blend_index.cpp 
  gl_330_blend_rtt.cpp 
  gl_330_buffer_type.cpp 
  gl_330_draw_instanced_array.cpp 
  gl_330_fbo_multisample_explicit_nv.cpp 
  gl_330_query_conditional.cpp 
  gl_330_query_counter.cpp 
  gl_330_query_occlusion.cpp 
  gl_330_query_timer.cpp 
  gl_330_sampler_anisotropy_ext.cpp 
  gl_330_sampler_filter.cpp 
  gl_330_sampler_object.cpp 
  gl_330_sampler_wrap.cpp 
  gl_330_texture_integer_rgb10a2ui.cpp 
  gl_330_texture_rect.cpp 
  gl_330_texture_swizzle.cpp 
  gl_400_blend_rtt.cpp 
  gl_400_draw_indirect.cpp 
  gl_400_fbo_layered.cpp 
  gl_400_fbo_multisample.cpp 
  gl_400_fbo_rtt_texture_array.cpp 
  gl_400_fbo_rtt.cpp 
  gl_400_fbo_shadow.cpp 
  gl_400_primitive_instanced.cpp 
  gl_400_primitive_smooth_shading.cpp 
  gl_400_primitive_tessellation.cpp 
  gl_400_program_64.cpp 
  gl_400_program_varying_blocks.cpp 
  gl_400_program_varying_structs.cpp 
  gl_400_sampler_array_nv.cpp 
  gl_400_sampler_array.cpp 
  gl_400_sampler_fetch.cpp 
  gl_400_texture_buffer_rgb.cpp 
  gl_400_texture_cube.cpp 
  gl_400_texture_derivative.cpp 
  gl_410_fbo_layered.cpp 
  gl_410_primitive_instanced.cpp 
  gl_410_primitive_tessellation_2.cpp 
  gl_410_primitive_tessellation_5.cpp 
  gl_410_program_64.cpp 
  gl_410_program_separate.cpp 
  gl_420_atomic_counter.cpp 
  gl_420_buffer_uniform.cpp 
  gl_420_clipping.cpp 
  gl_420_draw_base_instance.cpp 
  gl_420_draw_image_space_rendering.cpp 
  gl_420_fbo.cpp 
  gl_420_image_load.cpp 
  gl_420_image_store.cpp 
  gl_420_image_unpack.cpp 
  gl_420_interface_matching.cpp 
  gl_420_memory_barrier.cpp 
  gl_420_picking.cpp 
  gl_420_primitive_line_aa.cpp 
  gl_420_sampler_fetch.cpp 
  gl_420_sampler_gather.cpp 
  gl_420_test_depth_conservative.cpp 
  gl_420_texture_array.cpp 
  gl_420_texture_compressed.cpp 
  gl_420_texture_conversion.cpp 
  gl_420_texture_cube.cpp 
  gl_420_texture_pixel_store.cpp 
  gl_420_texture_storage.cpp 
  gl_420_transform_feedback_instanced.cpp 
  gl_430_atomic_counter.cpp 
  gl_430_direct_state_access_ext.cpp 
  gl_430_draw_vertex_attrib_binding.cpp 
  gl_430_draw_without_vertex_attrib.cpp 
  gl_430_fbo_invalidate.cpp 
  gl_430_fbo_srgb_decode.cpp 
  gl_430_fbo_without_attachment.cpp 
  gl_430_image_sampling.cpp 
  gl_430_image_store.cpp 
  gl_430_multi_draw_indirect.cpp 
  gl_430_program_compute_image.cpp 
  gl_430_program_compute.cpp 
  gl_430_program_subroutine.cpp 
  gl_430_query_conditional.cpp 
  gl_430_query_occlusion.cpp 
  gl_430_texture_buffer.cpp 
  gl_430_texture_copy.cpp 
  gl_430_texture_storage.cpp 
  gl_430_texture_view.cpp 
  gl_440_atomic_counter.cpp 
  gl_440_buffer_storage.cpp 
  gl_440_buffer_type.cpp 
  gl_440_fbo_depth_stencil.cpp 
  gl_440_fbo_without_attachment.cpp 
  gl_440_fbo.cpp 
  gl_440_query_occlusion.cpp 
  gl_440_sampler_wrap.cpp 
  gl_440_texture_compressed.cpp 
  gl_450_clip_control.cpp 
  gl_450_culling.cpp 
  gl_450_direct_state_access.cpp 
  gl_450_fbo_multisample_explicit.cpp 
  gl_450_query_conditional.cpp 
  gl_450_query_statistics_arb.cpp 
  gl_450_texture_barrier.cpp 
  gl_450_texture_derivative.cpp 
  gl_450_transform_feedback_arb.cpp 
  base_app.cpp 
  main.cpp )

